### ISSUE TITLE
Stateful component usage example

### ISSUE THREAD

**Issue by EduardJS** [perrin4869/react-stay-scrolled#98]
Hello! We're interested in using this ( since the `column-reverse` causes quite a few issues with our user base ).

But, I can't seem to figure out how to use this with a stateful component, given you only seem to be using it with simple functional components.

Please advise

**Comment by perrin4869** [comment]
@EduardJS If refactoring your component to use hooks or upgrading to `react-dom@16.8` is not an option, I think you should look at `v3`, which is the last version that supported a non-hook API...
Maybe you could try to make a new `StayScrolled` component based on the current API, something along the lines:

```javascript
<StayScrolled component="div" initialScroll={Infinity} render={({ stayScrolled, scrollBottom }) => (...)} />
```

**Comment by EduardJS** [comment]
Hey! I'm on 16.8.6 already ( didn't read into the Hook API ) but I guess it only works with functional components only. 

Will try refactoring it :) Learning something new in the process.

**Comment by EduardJS** [comment]
Also, just wondering. Is there any significant benefit with v7 over the v3 which wasn't using Hooks ? Regards

**Comment by perrin4869** [comment]
depends how you define benefit ;)
In general `v7`'s API is better designed and leaner, and you could use it as a base to re-implement `v3` if you wanted. Compare the `README.md` of both to see what I mean, `v7` is much simpler
But of course as far as accomplishing the goal, or performance-wise, there is no benefit
